### ISSUE TITLE
Different Numbers Cause the Gutter to Have Different Widths

### ISSUE THREAD

**Issue by Signynt** [nadavspi/obsidian-relative-line-numbers#10]
When scrolling through the lines the different widths of the numbers will cause the text to move back in forth, which is quite irritating and distracting.
Shown in the default Obsidian theme:

https://user-images.githubusercontent.com/67801159/171867928-a06e43d0-8105-4e30-9cc4-6e6ea878e196.mp4

**Comment by bew** [comment]
#16 was merged but I just installed this plugin and the behavior is still like OP.
Do you need to do a release so we can benefit from it?

**Comment by yv0x** [comment]
yes, we need a new release
alternatively you can clone the repo and do

- npm i
- npm run build

and copy the new main.js into your .obsidian/plugins/obsidian-relative-line-numbers

idk if that's the correct way to go about things though
