### ISSUE TITLE
Using a deprecated package: "@codemirror/gutter"

### ISSUE THREAD

**Issue by vultix** [nadavspi/obsidian-relative-line-numbers#13]
Just a heads up, opening the developer console in obsidian with this plugin enabled yields this error message:
```
Error: [CM6][obsidian-relative-line-numbers] Using a deprecated package: "@codemirror/gutter".
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at o (app.js:1:1547190)
    at anonymous (plugin:obsidian-relative-line-numbers:59:32)
    at e.<anonymous> (app.js:1:1547485)
    at app.js:1:235078
    at Object.next (app.js:1:235183)
    at s (app.js:1:233922)
```

**Comment by grantx2016** [comment]
+1

**Comment by grantx2016** [comment]
Has this plugin has been abandoned?

**Comment by d2718nis** [comment]
Seems like none of the issues could be fixed by @nadavspi. This plugin uses the other one created for the CodeMirror editor and literally just plugs it in Obsidian. So either it should be recreated from scratch or the author of the [other plugin](https://github.com/jsjoeio/codemirror-line-numbers-relative) should fix it on their end.

https://github.com/nadavspi/obsidian-relative-line-numbers/blob/f0bd4e97485c2414b4483afa3b199085e22870e3/main.ts#L2

**Comment by sohanglal** [comment]
+1

**Comment by RhvdG** [comment]
The error is still displayed inside Obsidian.

```
app.js:1 Error: [CM6][obsidian-relative-line-numbers] Using a deprecated package: "@codemirror/gutter".
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at o (app.js:1:2034861)
    at anonymous (plugin:obsidian-relative-line-numbers:59:32)
    at e.<anonymous> (app.js:1:2035156)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
```

**Comment by marchank0** [comment]
that's because this package is still [there](https://github.com/nadavspi/obsidian-relative-line-numbers/blob/4da2d3414459b0c4dc861ec6f1a1763fd5697030/esbuild.config.mjs#L29)

**Comment by massivebird** [comment]
> I believe this is what was causing Obsidian lag a lot. Hopefully #15 fixes this issue 🤞

That PR appears to have resolved the issue, but it hasn't been part of a release yet (the most recent release predates the merging of that PR). Plugins installed through the Obsidian client will only update when they push a new release.

For now, I've been able to apply the fix by [manually building the plugin](https://docs.obsidian.md/Plugins/Getting+started/Build+a+plugin#Step+1+Download+the+sample+plugin).
