### ISSUE TITLE
Are you going to release an update with support for iPad?

### ISSUE THREAD

**Issue by ravero** [nadavspi/obsidian-relative-line-numbers#18]
I saw that you merged PR #9. This is something that I need to complete my setup. Everytime I open the vault on iPad it disables the plugin, and then I need to re-enable on the desktop. Also, I wanted the plugin to work in iPad.

Let me know if you're updating the plugin or if its going to be discontinued. Otherwise I'll do a fork of it and bump the version.
Thanks

**Comment by Octo-Cellulose** [comment]
I am also hoping this gets fixed/updated to work with iPad.
