### ISSUE TITLE
Does this work work since the Live Preview update?

### ISSUE THREAD

**Issue by Hamm-J** [nadavspi/obsidian-relative-line-numbers#3]
Ever since the update which brought Live Preview, this extension has not been working for me. Regardless of if I have Live Preview enabled or disabled, this extension just does not work for me. 

I have tried installing from a fresh installation of Obsidian but it is still not working.

Am I missing something? Thanks.

**Comment by jgogstad** [comment]
Not working for me either

**Comment by ChrisBarfod** [comment]
It isn't working for me

**Comment by pyl** [comment]
How can i contribute to this to fix it? Looking for how to get started

**Comment by thisdotrob** [comment]
I also found the plugin wasn't working and have fixed a bug which I think may be the same as you are describing: #4

If you want to check it is the same bug, try toggling the plugin off and then on again after setting "Show line numbers" to on.

**Comment by grantx2016** [comment]
Any chance this plugin can be fixed?

**Comment by rolfaalders** [comment]
> I also found the plugin wasn't working and have fixed a bug which I think may be the same as you are describing: #4
> 
> If you want to check it is the same bug, try toggling the plugin off and then on again after setting "Show line numbers" to on.

Didn't work for me. :(
I'm really missing this plugin ... Hope it can be fixed soon

**Comment by thisdotrob** [comment]
Looks like it is not working when live preview is enabled. For me it works if I have "Use legacy editor" set to ON (with the caveat that the bug I mentioned before needs to be worked around).

**Comment by nadavspi** [comment]
Should be good in both Live Preview and Legacy editors now with 2.0.1. See #4.

**Comment by grantx2016** [comment]
Thanks heaps @nadavspi! IT' S ALIVE!!!! 🕺

**Comment by Hamm-J** [comment]
Works for me now @nadavspi ! Thanks so much for your work :)
